### PR TITLE
Development

### PR DESCRIPTION
**Pull request by ifylala**
Fixes #XX

**Description**
Using accordion, I have redesigned the FAQ page with 10 important FAQs to something more user friendly. I ensured I categorized the questions so it could help users easily view questions that really meets their needs. The redesign is also Mobile friendly. 
**Other information**
It was a nice experience redesigning the FAQ page.

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by kgodey** [comment]
Is this something you can deploy using GitHub Pages on your fork of the repo?

**Comment by ifylala** [comment]
> Is this something you can deploy using GitHub Pages on your fork of the repo?

okay I would deploy on github pages and share the url

**Comment by kgodey** [comment]
I messaged you on Slack, but GitHub Pages is documented on https://pages.github.com/.

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this PR.

**Pull request closed without merging**
