### PR TITLE
Sample FAQs page with 10 most important FAQs

### LINKED ISSUE #30: Create page with 10 most important FAQs
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
Review CC’s FAQs and design a user friendly page that incorporates what you believe to be the ten most important ones. Make a new folder in this repository with your HTML and CSS files and submit it as a pull request.

Usage of [CC Vocabulary](https://opensource.creativecommons.org/cc-vocabulary/) is recommended but not required.

### PR DESCRIPTION
**Pull request by chidexebere**
Fixes #30

**Description**

This is a sample redesigned the FAQs page with accordions picking only ten FAQs from the main FAQs page.
This greatly reduces a lot of scrolling; providing a better user experience.

**Other information**

This design can be incorporated into the main FAQs page and also solve issue #29

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by kgodey** [comment]
@chidexebere is this deployed on GitHub Pages anywhere?

**Comment by chidexebere** [comment]
@kgodey yes, on the gh-pages branch of the repo to be merged

**Comment by kgodey** [comment]
Could you provide a link to the deployment?

**Comment by chidexebere** [comment]
Okay @kgodey , here is it https://chidexebere.github.io/faq/10-FAQs/

**Comment by kgodey** [comment]
Great, thank you @chidexebere! I like the accordion design and the live search and the design and nice and clean. Good job :)

I won't be merging this PR since it's just an exercise with 10 FAQs meant to get you to start thinking about the larger project but I hope that it helps you with your final application! You can count this as your contribution and start work on your draft (use this template: https://docs.google.com/document/d/1qJF51MNk2KD_A0g3e3LRFmK-p5DD4owg7lXByjQWclM/). Please ask us on Slack if you have questions about the project or Creative Commons in general or anything else.

**Comment by chidexebere** [comment]
Okay, thank you @kgodey

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this PR.

**Pull request closed without merging**
